# Generated by Django 2.2.1 on 2019-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dantza', '0002_auto_20190607_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armairua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zbk', models.IntegerField()),
                ('arropa', models.ManyToManyField(blank=True, to='dantza.ArropaMota')),
                ('materiala', models.ManyToManyField(blank=True, to='dantza.Materiala')),
            ],
        ),
    ]
