# Generated by Django 2.2.1 on 2019-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dantza', '0003_armairua'),
    ]

    operations = [
        migrations.AddField(
            model_name='armairua',
            name='zehaztapenak',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='armairua',
            name='zbk',
            field=models.CharField(max_length=100),
        ),
    ]
