# Generated by Django 2.2.2 on 2019-07-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dantza', '0004_auto_20190607_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oharra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mezua', models.CharField(max_length=200)),
                ('hartzailea', models.CharField(choices=[('MA', 'Material arduraduna'), ('AA', 'Arropa arduraduna')], max_length=10)),
                ('data', models.DateTimeField(verbose_name='Oharraren data')),
            ],
        ),
    ]
