# Generated by Django 2.2.2 on 2019-07-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dantza', '0005_oharra'),
    ]

    operations = [
        migrations.AddField(
            model_name='oharra',
            name='igorlea',
            field=models.CharField(default='auto', max_length=100),
        ),
    ]
