# Generated by Django 2.2.2 on 2019-07-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dantza', '0006_oharra_igorlea'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailegua',
            name='dantza_taldea',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
