# Generated by Django 2.2.2 on 2019-07-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dantza', '0007_mailegua_dantza_taldea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekitaldia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=200)),
                ('data', models.DateTimeField(verbose_name='aktuazio data')),
                ('lekua', models.CharField(max_length=100)),
                ('dirua', models.IntegerField(blank=True)),
                ('beste_info', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
