# Generated by Django 2.2.2 on 2019-07-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dantza', '0008_ekitaldia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekitaldia',
            name='dantzariak',
            field=models.ManyToManyField(blank=True, to='dantza.Dantzaria'),
        ),
    ]
