# Generated by Django 2.2.2 on 2019-07-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dantza', '0010_auto_20190711_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='DantzaDock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dock', models.FileField(upload_to='dantzaDock/')),
                ('dantza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dantza.Dantza')),
            ],
        ),
    ]
