# Generated by Django 2.2.2 on 2019-07-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dantza', '0011_dantzadock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dantza',
            name='iraupena',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dantzadock',
            name='dock',
            field=models.CharField(max_length=500),
        ),
    ]
