# Generated by Django 2.2.2 on 2019-07-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dantza', '0012_auto_20190711_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='arropa',
            name='mailegatua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tresna',
            name='mailegatua',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oharra',
            name='hartzailea',
            field=models.CharField(choices=[('MA', 'Material arduraduna'), ('AA', 'Arropa arduraduna'), ('DT', 'Dantzaria')], max_length=10),
        ),
    ]
